name = "your-first-customer"
compatibility_date = "2024-12-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "yfc-db"
database_id = "f65521c2-de37-401a-89ef-5464b5442a73"

[[kv_namespaces]]
binding = "CACHE"
id = "b20df1bda1f64ff88c721b84b065e23e"

[vars]
CLAUDE_MODEL = "claude-sonnet-4-6"
